apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: app-ti
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: app1
          image: httpd:2.4
          volumeMounts:
          - name: index-config1
            mountPath: /usr/local/apache2/htdocs/
        - name: app2
          image: httpd:2.4
          volumeMounts:
          - name: index-config2
            mountPath: /usr/local/apache2/htdocs/
        - name: nginx
          image: nginx:alpine
          ports:
          - containerPort: 81
          volumeMounts:
          - name: nginx-proxy-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
        - name: index-config1
          hostPath:
            path: /home/ubuntu/App1/
        - name: nginx-proxy-config
          configMap:
            name: config-map
        - name: index-config2
          hostPath:
            path: /home/ubuntu/App2/
           
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        keepalive_timeout  65;
        upstream webapp {
            server 127.0.0.1;
        }
        server {
            listen 81;
            listen [::]:81 ipv6only=on default_server;
            location / {
                proxy_pass         http://localhost:5000;
            }
            location /app2 {
                proxy_pass         http://localhost:80/index.html;
                proxy_redirect     off;
            }
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: service-proxy
  namespace: default
spec:
  ports:
  - nodePort: 31100
    port: 81
    protocol: TCP
    targetPort: 81
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
