# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deployDevelopment:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "a6:92:78:56:74:59:3b:f3:7f:a7:69:ed:7f:99:af:29"
      - run:
         name: "Archivo yaml" 
         command: |
            cd ./Kube
            scp -o StrictHostKeyChecking=no -r ./* eubuntu@3.223.125.157:~/
            ssh -o StrictHostKeyChecking=no eubuntu@3.223.125.157 "kubectl delete all --all"
            ssh -o StrictHostKeyChecking=no eubuntu@3.223.125.157 "kubectl delete all --all"
            ssh -o StrictHostKeyChecking=no eubuntu@3.223.125.157 "kubectl apply -f deployment.yaml"
    
  productionDeploy:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "f4:1c:cf:8e:31:a2:93:4a:4a:6d:58:18:f9:5c:19:64"
      - run:
         name: "Archivo yaml" 
         command: |
            cd ./Kube
            scp -o StrictHostKeyChecking=no -r ./* ubuntu@34.201.47.241:~/
            ssh -o StrictHostKeyChecking=no ubuntu@34.201.47.241 "kubectl delete all --all"
            ssh -o StrictHostKeyChecking=no ubuntu@34.201.47.241 "kubectl delete all --all"
            ssh -o StrictHostKeyChecking=no ubuntu@34.201.47.241 "kubectl apply -f deployment.yaml"
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

 
    


workflows:
  version: 2
  normal_run:
    jobs:
      - deployDevelopment:
          filters:
            branches:
              only:
                - master
      - request-testing:
          type: approval
          requires:
            - deployDevelopment
      - productionDeploy:
          requires:
            - request-testing
          filters:
            branches:
              only:
                - master  